name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      organization_code:
        description: 'Organization Code'
        required: true
        default: 'mf'
      lob_code:
        description: 'lob Code'
        required: true
        default: 'daia'
      app_code:
        description: 'Application Code'
        required: true
        default: 'azraaa'
      application_name:
        description: 'Infra repo name'
        required: true
        default: 'mf-dt-azrabc-sampleapp-infra-repo'
      application_platform:
        description: 'Application Platform'
        required: true
        default: 'mf-dt-azrabc-sampleapp-app-repo'
      environments:
        description: "Environments JSON"
        required: true
        default: '[{"name":"Development","code":"dev","subscription_id":""},{"name":"QA","code":"qat","subscription_id":""}]'
      # Add more as needed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Use workflow input, fallback to secrets/defaults if missing
      FOUNDATION_REPO: ${{ github.event.inputs.foundation_repo || 'mf-dt-azrabc-sampleapp-foundation-repo' }}
      INFRA_REPO: ${{ github.event.inputs.infra_repo || 'mf-dt-azrabc-sampleapp-infra-repo' }}
      APP_REPO: ${{ github.event.inputs.app_repo || 'mf-dt-azrabc-sampleapp-app-repo' }}
      GITHUB_ORGANIZATION: ${{ github.event.inputs.organization || 'McCainFoods' }}
      REPO_VISIBILITY: ${{ github.event.inputs.repo_visibility || 'private' }}

      # ... (other secrets and envs as above)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: (Optional) Load extra config from input.json
        run: |
          if [ -f input.json ]; then
            echo "input.json present"
          else
            echo '{}' > input.json
          fi

      - name: Generate terraform.tfvars from template, env, and input.json
        run: python generate_tfvars.py

      - name: Display generated tfvars (debug)
        run: cat terraform.tfvars
